#pragma config(Sensor, S1,     range,          sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
float distance = 0;

task displayTask(){
	while(true){
		displayBigTextLine(3,"Distance:");
		displayBigTextLine(5,"%d", distance);
	}
}
task rangeSensorTask(){
	while(true){
		distance= getUSDistance(range);
	}
}
task main()
{
	while(true){
		startTask(displayTask);
		startTask(rangeSensorTask);
	}
}
