#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

string state;
long bumpCount = 0;

task touchSensorTask()
{
	while(true)
	{
		if (getTouchValue(touchSensor) == 1) // touch sensor is pressed
		{
				state = "pressed";

		}
		else if (getTouchValue(touchSensor) == 0)
		{
				state = "unpressed";
		}
		bumpCount = getBumpedValue(touchSensor);

	}

}

task sensorState()
{
	while(true)
	{
		displayBigTextLine(5, "%s", state);
		displayBigTextLine(9, "bumps: %d", bumpCount);
	}
}



task main()
{
	startTask(touchSensorTask);
	startTask(sensorState);

	while(true)
	{
		sleep(100);

	}


}
