#pragma config(Sensor, S1,     touchSensor,    sensorNone)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float desiredAngle = (((120.0/2) * (2* PI)) *(2/58.0))*(180/PI);
long bumpCount = 0;
int counter = -1;
string state;

task rotate360()
{
	while(true)
	{
		if (getTouchValue(touchSensor) == 1) // touch sensor is pressed
		{
				counter++;


		}
		else if (getTouchValue(touchSensor) == 0)
		{
				state = "unpressed";
			//	sleep(8500);
		}
		bumpCount = getBumpedValue(touchSensor);

	}

}


task main()
{
	startTask(rotate360);
	while (true)
	{
		//resetBumpedValue(touchSensor);

		if (counter >= 0)
		{
			if(bumpCount % 2 == 0)
			{
				setMotorSyncEncoder(rightMotor,leftMotor,-50,desiredAngle,40);
				//resetBumpedValue(touchSensor);
			}
			else
			{
				setMotorSyncEncoder(rightMotor, leftMotor, 50, desiredAngle, 40);
				//resetBumpedValue(touchSensor);
			}
		}
	}


}
