#pragma config(Sensor, S1,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define DATA_SERIES_0 0
#define DATA_SERIES_1 1

//float rate, movingAvgRate;
//const int bufferSize = 5;
//float avg;
float tolerance = 0.2;
//float gyroBuffer[bufferSize];
float desiredAngle1 = (120.0/2)* (-((2*PI)/3)) * (2/58.0) * (180/PI); // -2pi/3
//float desiredAngle2 = (120.0/2) * (PI/2) * (2/58.0) * (180/PI); // Pi/2
float currentAngle = 0;
float error;
float increment = 0;
const int slewRate = 10;
const float k = 2;
int desiredPower, currentPower;



task gyroTask()
{
	while(true)
	{
			desiredPower = 0;
			currentAngle = -(getGyroDegrees(gyroSensor) * (PI/180));
			error = (desiredAngle1 - currentAngle);
			if(abs(error) > tolerance)
			{
				desiredPower = k * error;


				if(currentAngle < desiredAngle1)
				{

					if(currentPower + slewRate < desiredPower)
					{
						currentPower += slewRate;
					}
					else
					{
						currentPower = desiredPower;
					}
					//if(currentPower > 30)
					//currentPower = 30;
				}
				else
				{

					if(currentPower - slewRate > desiredPower)
					{
						currentPower -= slewRate;
					}
					else
					{
						currentPower = desiredPower;
					}
					//if(currentPower < -30)
						//currentPower = -30

				}
			}
			else
			{
				currentPower = 0;
			}

			if(currentAngle < desiredAngle1)
			{
				increment += 	(slewRate * (PI/180));
				currentAngle = -(getGyroDegrees(gyroSensor) * (PI/180));
			}
			else
				if(currentAngle > desiredAngle1)
				{
					increment -= (slewRate * (PI/180));
					currentAngle = -(getGyroDegrees(gyroSensor) * (PI/180));
				}
				setMotorSync(rightMotor, leftMotor, 100, currentPower);
				sleep(100);
			}



	}






task main()
{
	startTask(gyroTask);
	while(true)
	{
		sleep(200);
	}


}
