#pragma config(Sensor, S1,     colorSensor,    sensorNone)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float desiredAngle = (((120.0/2) * (2* PI)) *(2/58.0))*(180/PI);
long bumpCount = 0;
int counter = -1;
string state;

task rotate360()
{
	while(true)
	{
		if (getColorName(colorSensor) == "Color name: black") // color sensor is activated
		{
				setMotorSyncEncoder(rightMotor, leftMotor, -50, desiredAngle, 40);


		}
		else if (getColorName(colorSensor) == 0)
		{
				state = "unpressed";
			
		}
		color = getColorName(colorSensor);

	}

}


task main()
{
	startTask(rotate360);
	while (true)
	{
		if (counter >= 0)
		{
			if(bumpCount % 2 == 0)
			{
				setMotorSyncEncoder(rightMotor,leftMotor,-50,desiredAngle,40);
			}
			else
			{
				setMotorSyncEncoder(rightMotor, leftMotor, 50, desiredAngle, 40);
			}
		}
	}


}
