#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color)
#pragma config(Motor,  motorB,          LEFT,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          RIGHT,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


int currentPower = 25, k = 3,slewRate = 5;
float angleU = 0, nTurnRatio = 0;

task controllerTask()
{
	while(true){
		displayBigTextLine(3,"C: %d",getColorReflected(colorSensor));

		if(getColorReflected(colorSensor) < 10){
				currentPower = - currentPower;
				sleep(200);
			}
		//setMotorSyncEncoder(RIGHT,LEFT,nTurnRatio,angleU,currentPower);

	}
}// End of Task


task main()
{
	startTask(controllerTask);
	while(true){
		displayCenteredBigTextLine(6, "%.2f", currentPower);
		setMotorSyncEncoder(RIGHT,LEFT,nTurnRatio,angleU,currentPower);
	}
}
