#pragma config(Sensor, S1,     colorSensor,    sensorEV3_Color)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//follow the black line on the right edge
int leftPower, rightPower = 10;
task followLine(){
	while(true){
		while(getColorReflected(colorSensor) > 10){
			leftPower = 10;
			rightPower = 25;

		}
		while(getColorReflected(colorSensor) < 10){
			leftPower = 25;
			rightPower = 10;
		}
	}
}
task main(){
	while(getColorReflected(colorSensor) > 10){
		setMotorSync(leftMotor, rightMotor, 0, 10);
	}
	startTask(followLine);
	while(true){
		setMotor(leftMotor, leftPower);
		setMotor(rightMotor, rightPower);
	}
}
